### ISSUE TITLE
Site Structure Address Points

### ISSUE THREAD

**Issue by dawnblanchard-DOIT** [NENA911/NG911GISDataModel#48] opened 2022-12-14 16:02 UTC
The data model standard lists the Elevation field (in SiteStructureAddressPoints) as a width of 6, however the geodatabase uses a short integer field type that can only store up to a length of 5. Should we switch this to a long integer?.

**Comment by geofinne** [comment] 2022-12-14 16:26
Hi @dawnblanchard-DOIT , this is duplicated from the issue I reported.  @tomneer , this one can be closed.

**Comment by tomneer** [comment] 2022-12-14 18:19
Duplicate of #46, closing as duplicate

**Closed as completed by tomneer** 2022-12-14 18:19 UTC
Labels: duplicate
